version: '3'
services:
  service-booking:
    build:
      context: ./serviceBooking
    ports:
      - 5004:5004
    container_name: service-booking
    networks:
      - my-network

  service-kiwi:
    build:
      context: ./serviceKiwi
    ports:
      - 5001:5001
    container_name: service-kiwi
    networks:
      - my-network

  service-skyscanner:
    build:
      context: ./serviceSkyscanner
    ports:
      - 5003:5003
    container_name: service-skyscanner
    networks:
      - my-network

  service-trip:
    build:
      context: ./serviceTrip
    ports:
      - 5002:5002
    container_name: service-trip
    networks:
      - my-network

  broker:
    build:
      context: ./Broker
    ports:
      - 5005:5005
    container_name: broker
    depends_on:
      - service-booking
      - service-kiwi
      - service-skyscanner
      - service-trip
    networks:
      - my-network

  client:
    build:
      context: ./Client
    ports:
      - 5000:5000
    container_name: client
    depends_on:
      - broker
    networks:
      - my-network

networks:
  my-network:
